package com.zhiye.model;

import java.util.Date;

public class DataInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_entry_ctrl.ENTRY_CTRL_ID
     *
     * @mbggenerated Tue May 03 17:22:34 CST 2016
     */
    private Integer entryCtrlId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_entry_ctrl.USER_INF_ID
     *
     * @mbggenerated Tue May 03 17:22:34 CST 2016
     */
    private Integer userInfId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_entry_ctrl.LOGON_TIME
     *
     * @mbggenerated Tue May 03 17:22:34 CST 2016
     */
    private Date logonTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_entry_ctrl.SESSION_ID
     *
     * @mbggenerated Tue May 03 17:22:34 CST 2016
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_entry_ctrl.SERVER
     *
     * @mbggenerated Tue May 03 17:22:34 CST 2016
     */
    private String server;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_entry_ctrl.ENTRY_CTRL_ID
     *
     * @return the value of msg_entry_ctrl.ENTRY_CTRL_ID
     *
     * @mbggenerated Tue May 03 17:22:34 CST 2016
     */
    public Integer getEntryCtrlId() {
        return entryCtrlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_entry_ctrl.ENTRY_CTRL_ID
     *
     * @param entryCtrlId the value for msg_entry_ctrl.ENTRY_CTRL_ID
     *
     * @mbggenerated Tue May 03 17:22:34 CST 2016
     */
    public void setEntryCtrlId(Integer entryCtrlId) {
        this.entryCtrlId = entryCtrlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_entry_ctrl.USER_INF_ID
     *
     * @return the value of msg_entry_ctrl.USER_INF_ID
     *
     * @mbggenerated Tue May 03 17:22:34 CST 2016
     */
    public Integer getUserInfId() {
        return userInfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_entry_ctrl.USER_INF_ID
     *
     * @param userInfId the value for msg_entry_ctrl.USER_INF_ID
     *
     * @mbggenerated Tue May 03 17:22:34 CST 2016
     */
    public void setUserInfId(Integer userInfId) {
        this.userInfId = userInfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_entry_ctrl.LOGON_TIME
     *
     * @return the value of msg_entry_ctrl.LOGON_TIME
     *
     * @mbggenerated Tue May 03 17:22:34 CST 2016
     */
    public Date getLogonTime() {
        return logonTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_entry_ctrl.LOGON_TIME
     *
     * @param logonTime the value for msg_entry_ctrl.LOGON_TIME
     *
     * @mbggenerated Tue May 03 17:22:34 CST 2016
     */
    public void setLogonTime(Date logonTime) {
        this.logonTime = logonTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_entry_ctrl.SESSION_ID
     *
     * @return the value of msg_entry_ctrl.SESSION_ID
     *
     * @mbggenerated Tue May 03 17:22:34 CST 2016
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_entry_ctrl.SESSION_ID
     *
     * @param sessionId the value for msg_entry_ctrl.SESSION_ID
     *
     * @mbggenerated Tue May 03 17:22:34 CST 2016
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_entry_ctrl.SERVER
     *
     * @return the value of msg_entry_ctrl.SERVER
     *
     * @mbggenerated Tue May 03 17:22:34 CST 2016
     */
    public String getServer() {
        return server;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_entry_ctrl.SERVER
     *
     * @param server the value for msg_entry_ctrl.SERVER
     *
     * @mbggenerated Tue May 03 17:22:34 CST 2016
     */
    public void setServer(String server) {
        this.server = server;
    }
}