package com.zhiye.model;

import java.util.Date;

public class MsgKeywords {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column msg_keywords.KW_ID
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	private Integer kwId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column msg_keywords.KW_CONTENT
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	private String kwContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column msg_keywords.KW_CRETIME
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	private Date kwCretime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column msg_keywords.KW_REASON
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	private String kwReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column msg_keywords.KW_CREATER
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	private Integer kwCreater;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column msg_keywords.KW_STATUS
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	private String kwStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column msg_keywords.KW_MODIFY
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	private Integer kwModify;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column msg_keywords.KW_MODTIME
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	private Date kwModtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_keywords.KW_ID
	 * @return  the value of msg_keywords.KW_ID
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	public Integer getKwId() {
		return kwId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_keywords.KW_ID
	 * @param kwId  the value for msg_keywords.KW_ID
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	public void setKwId(Integer kwId) {
		this.kwId = kwId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_keywords.KW_CONTENT
	 * @return  the value of msg_keywords.KW_CONTENT
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	public String getKwContent() {
		return kwContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_keywords.KW_CONTENT
	 * @param kwContent  the value for msg_keywords.KW_CONTENT
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	public void setKwContent(String kwContent) {
		this.kwContent = kwContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_keywords.KW_CRETIME
	 * @return  the value of msg_keywords.KW_CRETIME
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	public Date getKwCretime() {
		return kwCretime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_keywords.KW_CRETIME
	 * @param kwCretime  the value for msg_keywords.KW_CRETIME
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	public void setKwCretime(Date kwCretime) {
		this.kwCretime = kwCretime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_keywords.KW_REASON
	 * @return  the value of msg_keywords.KW_REASON
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	public String getKwReason() {
		return kwReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_keywords.KW_REASON
	 * @param kwReason  the value for msg_keywords.KW_REASON
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	public void setKwReason(String kwReason) {
		this.kwReason = kwReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_keywords.KW_CREATER
	 * @return  the value of msg_keywords.KW_CREATER
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	public Integer getKwCreater() {
		return kwCreater;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_keywords.KW_CREATER
	 * @param kwCreater  the value for msg_keywords.KW_CREATER
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	public void setKwCreater(Integer kwCreater) {
		this.kwCreater = kwCreater;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_keywords.KW_STATUS
	 * @return  the value of msg_keywords.KW_STATUS
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	public String getKwStatus() {
		return kwStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_keywords.KW_STATUS
	 * @param kwStatus  the value for msg_keywords.KW_STATUS
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	public void setKwStatus(String kwStatus) {
		this.kwStatus = kwStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_keywords.KW_MODIFY
	 * @return  the value of msg_keywords.KW_MODIFY
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	public Integer getKwModify() {
		return kwModify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_keywords.KW_MODIFY
	 * @param kwModify  the value for msg_keywords.KW_MODIFY
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	public void setKwModify(Integer kwModify) {
		this.kwModify = kwModify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column msg_keywords.KW_MODTIME
	 * @return  the value of msg_keywords.KW_MODTIME
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	public Date getKwModtime() {
		return kwModtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column msg_keywords.KW_MODTIME
	 * @param kwModtime  the value for msg_keywords.KW_MODTIME
	 * @mbggenerated  Fri Apr 29 14:20:17 CST 2016
	 */
	public void setKwModtime(Date kwModtime) {
		this.kwModtime = kwModtime;
	}
}